apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJhY3JjaGFybGllaHlwZXJhLmF6dXJlY3IuaW8iOiB7CgkJCSJhdXRoIjogIllXTnlZMmhoY214cFpXaDVjR1Z5WVRwVlVHNVBjVWRYZDJGQlV6UnpZVU4yU0dwM1RsbHVkVE51Wm1FOWVrUmFSUT09IgoJCX0KCX0KfQ==
kind: Secret
metadata:
  name: acr-azure-auth
  namespace: charlie
type: kubernetes.io/dockerconfigjson
