apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
  - ./deployment.yaml
  - ./ingress.yaml
  - ./ingress-ssl.yaml
  - ./redirect-to-https.yaml
  - ./service.yaml
