---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: charlie-server

resources:
  - ./hypera-ca-secret.yaml
  - ./acr-auth.yaml
  - ./deployment.yaml
  - ./ingress-web.yaml
  - ./ingress-websecure.yaml
  - ./redirect-to-https.yaml
  - ./service.yaml

images:
  - name: acrcharliehypera.azurecr.io/charlie-server
    newTag: v0.0.1
