apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

commonLabels:
  app: charlie-server-dev

namespace: charlie

resources:
  - ./deployment.yaml
  - ./ingress.yaml
  - ./ingress-ssl.yaml
  - ./redirect-to-https.yaml
  - ./service.yaml

images:
- name: charlie-server
  newName: acrcharliehypera.azurecr.io/charlie-server
  newTag: IMAGE_TAG
